### ISSUE TITLE
ultraman-oji cannot be used as a custom emoji of Slack

### ISSUE THREAD

**Issue by shisama** [ryosuke-oshida/emOjis#1]
The size has to be less than 128kb to add the image as a custom emoji in Slack.
The ultraman-oji is too big to join the slack.
I believe that the ultraman-oji won’t be weak even if the size is smaller.
So I'd appreciate it if you could make it smaller than 128kb.

**Comment by ryosuke-oshida** [comment]
I have already fixed this issue. Thanks! Ultraman never gets weaker!
